// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUM9q_SV4uFGYFEr41N5_zh0vCuyOhwwM',
    appId: '1:1058069644988:web:bf4ae18b2ca0a781f532b9',
    messagingSenderId: '1058069644988',
    projectId: 'recipeal-d9471',
    authDomain: 'recipeal-d9471.firebaseapp.com',
    storageBucket: 'recipeal-d9471.appspot.com',
    measurementId: 'G-JK5WZVLS7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtrRzcqdCYC3GYWp--rro__J9BX4YxGU',
    appId: '1:1058069644988:android:14a22f9d028c3943f532b9',
    messagingSenderId: '1058069644988',
    projectId: 'recipeal-d9471',
    storageBucket: 'recipeal-d9471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKzprsbRCbrg26iiee8m6bhx-vF_G5WLI',
    appId: '1:1058069644988:ios:5cbfd666e71b1602f532b9',
    messagingSenderId: '1058069644988',
    projectId: 'recipeal-d9471',
    storageBucket: 'recipeal-d9471.appspot.com',
    iosBundleId: 'recipeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKzprsbRCbrg26iiee8m6bhx-vF_G5WLI',
    appId: '1:1058069644988:ios:3420c9a2086f843bf532b9',
    messagingSenderId: '1058069644988',
    projectId: 'recipeal-d9471',
    storageBucket: 'recipeal-d9471.appspot.com',
    iosBundleId: 'com.example.foodForThought',
  );
}
