// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADLLcs4mQCH1RTqC4wdd0b_-fOBeoe140',
    appId: '1:69287062119:web:bd01f4be1b04812abe82c2',
    messagingSenderId: '69287062119',
    projectId: 'tender-d2d03',
    authDomain: 'tender-d2d03.firebaseapp.com',
    storageBucket: 'tender-d2d03.appspot.com',
    measurementId: 'G-689294CY74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw3eSyKvDlU0BxuPIU8yEPOSGoLoVWhms',
    appId: '1:69287062119:android:61301db514725622be82c2',
    messagingSenderId: '69287062119',
    projectId: 'tender-d2d03',
    storageBucket: 'tender-d2d03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo1N0zGHa5L17_oiv3GG-ykYnOrtLqayg',
    appId: '1:69287062119:ios:951a42943cb5aa46be82c2',
    messagingSenderId: '69287062119',
    projectId: 'tender-d2d03',
    storageBucket: 'tender-d2d03.appspot.com',
    iosBundleId: 'com.example.tender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo1N0zGHa5L17_oiv3GG-ykYnOrtLqayg',
    appId: '1:69287062119:ios:951a42943cb5aa46be82c2',
    messagingSenderId: '69287062119',
    projectId: 'tender-d2d03',
    storageBucket: 'tender-d2d03.appspot.com',
    iosBundleId: 'com.example.tender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADLLcs4mQCH1RTqC4wdd0b_-fOBeoe140',
    appId: '1:69287062119:web:78729be1b49ef686be82c2',
    messagingSenderId: '69287062119',
    projectId: 'tender-d2d03',
    authDomain: 'tender-d2d03.firebaseapp.com',
    storageBucket: 'tender-d2d03.appspot.com',
    measurementId: 'G-C868KTZ2QW',
  );
}
